### ISSUE TITLE
Rendering - Objects pop in and out when zooming in some toys.

### ISSUE THREAD

**Issue by RaymondMitchell-GG** [GarageGames/Torque2D#53] opened 2013-04-09 17:28 UTC
In the Truck toy and the DeathBall toy, when you zoom in some of the sprites pop in and out. 

Expected: Sprites that are on screen render appropriately.

Steps to reproduce:
 1. Start the sandbox and load the Truck toy.
 2. Zoom in slowly with the mouse wheel.
 3. Observe as you zoom in, different objects dissappear and reappear.

Note: This looks like a sorting/culling issue.

**Comment by greenfire27** [comment] 2015-10-20 20:15
I stumbled upon this while looking for the cause of some weird behavior that I've been seeing in my game when I zoom the camera.  A quick look at the code shows that we're clearly doing this twice as Simon pointed out.  I'll try to fix it and put in a pull request, but I think it's sad that we had a fix for over a year and it never made it into the code.  

Thanks for finding this Simon!

**Comment by capnlove** [comment] 2015-10-20 21:17
Always a pleasure!

**Comment by greenfire27** [comment] 2015-10-27 13:06
Fixed in dev.

**Closed by greenfire27** 2015-10-27 13:06 UTC
