### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by nounoursheureux** [GarageGames/Torque2D#252] opened 2015-08-21 17:11 UTC
OS: ArchLinux
GCC version: 5.2.0
It fails on the `master` and `development` branches with the same error message:
```
In file included from ../../source/gui/guiControl.h:45:0,
                 from ../../source/2d/core/ImageFrameProviderCore.h:51,
                 from ../../source/2d/core/ImageFrameProvider.h:27,
                 from ../../source/2d/core/ImageFrameProvider.cc:23:
../../source/platform/event.h:152:49: error: ‘data’ was not declared in this scope
 const U32 PacketReceiveEventHeaderSize = Offset(data,PacketReceiveEvent);
```

**Comment by brentdewe** [comment] 2015-09-07 18:42
I had the same problem, also Arch Linux gcc 5.2.0.

The problem is that the code does not take gcc versions greater than 4.x into account.
It can be fixed by changing line 152 of file `engine/source/platform/types.h` from
```
#if !defined(TORQUE_COMPILER_GCC) || (__GNUC__ < 3)
```
to
```
#if !defined(TORQUE_COMPILER_GCC) || (__GNUC__ < 3) || (__GNUC__ > 4)
```

**Comment by jamesu** [comment] 2015-11-12 12:18
You might want to define it as the standard offsetof macro ( see https://github.com/GarageGames/Torque3D/commit/5d89ab126dff69dfa087b4435357c4bfc942c99d )

**Comment by greenfire27** [comment] 2015-11-12 13:45
Great suggestion.  I'll look into offsetof.  I assume though that this is only used in T3D for consoles.  I know T3D currently has the same code as ours and doesn't solve the problem of what to do with GCC 5.x compilers.  I put a question out to the T3D community [here](http://forums.torque3d.org/viewtopic.php?f=10&t=424).  Maybe that helps shed some light on the situation.

**Comment by greenfire27** [comment] 2015-11-14 17:59
Based on the above I've added a statement for GCC 5.x compilers.  It uses the standard offsetof for the offset and the "_offset_normal" for OffsetNonConstants.  It will be in dev.  Those of you with this issue should test when you get a chance.

**Comment by brentdewe** [comment] 2015-11-14 22:26
It compiles without errors now. Thank you.

**Comment by greenfire27** [comment] 2015-11-14 22:55
Great! Mission accomplished.

**Closed by greenfire27** 2015-11-14 22:55 UTC
Labels: Linux, Solution Found
